language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: 
  - pip install python-coveralls
  - pip install -r requirements.txt
# command to run tests
script: 
  - python -m pytest tests --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report
after_success: 
  - coveralls